spring.application.name=sistemaalquiler

# Configuración de la base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/Peliculas
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=tu_root
spring.datasource.password=tu_123mfv
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Esta propiedad permite que Spring actualice las tablas si no existen
spring.jpa.hibernate.ddl-auto=update

# Configuración de la consola H2 (opcional)
# Si deseas usar H2 en memoria, puedes descomentar esta parte y comentar la configuración de MySQL.
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=password
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.h2.console.enabled=true
